using BUTR.Site.NexusMods.Server.Models.Database;

namespace BUTR.Site.NexusMods.Server.Repositories;

public interface ICrashReportToMetadataEntityRepositoryRead : IRepositoryRead<CrashReportToMetadataEntity>;
public interface ICrashReportToMetadataEntityRepositoryWrite : IRepositoryWrite<CrashReportToMetadataEntity>, ICrashReportToMetadataEntityRepositoryRead;