using BUTR.Site.NexusMods.Server.Models.Database;

namespace BUTR.Site.NexusMods.Server.Repositories;

public interface INexusModsModToFileUpdateEntityRepositoryRead : IRepositoryRead<NexusModsModToFileUpdateEntity>;
public interface INexusModsModToFileUpdateEntityRepositoryWrite : IRepositoryWrite<NexusModsModToFileUpdateEntity>, INexusModsModToFileUpdateEntityRepositoryRead;