using BUTR.Site.NexusMods.Server.Models.Database;

namespace BUTR.Site.NexusMods.Server.Repositories;

public interface INexusModsUserToSteamWorkshopModEntityRepositoryRead : IRepositoryRead<NexusModsUserToSteamWorkshopModEntity>;
public interface INexusModsUserToSteamWorkshopModEntityRepositoryWrite : IRepositoryWrite<NexusModsUserToSteamWorkshopModEntity>, INexusModsUserToSteamWorkshopModEntityRepositoryRead;